[tool.poetry]
name = "python-energie-prijs-verwerking"
version = "0.1.0"
description = ""
authors = ["Theo van der Sluijs <theo@vandersluijs.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"
APScheduler = "3.10.0"
PyYAML = "^6.0.1"
requests = "^2.32.3"
datacollectors = "^0.7.7"
numpy = "^1.26.4"
pandas = "^2.2.2"
python-dateutil = "^2.9.0.post0"
entsoe-py = "^0.6.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
